services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitcrocs-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - '3001:3001'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fitcrocs-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '4174:5173'
